{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "test2.serviceAccountName" . }}
  labels:
{{ include "test2.labels" . | indent 4 }}
{{- end -}}
